### ISSUE TITLE
Allow to compare Date

### ISSUE THREAD

**Issue by FabienSalles** [K-Phoen/rulerz#89] opened 2017-09-05 12:18 UTC
I used rulerz 1.9.1 in a project. I updated it to the lateast version (0.20.4) and my specifications classes with date comparison wasn't working anymore. 

Example of existing specification :

```php
class LeaderIsRequired extends AbstractSpecification
{
    private $mandatoryDate;

    public function __construct(int $mandatoryDay)
    {
        $this->mandatoryDate = Chronos::now()->addDay($mandatoryDay);
    }

    public function getRule()
    {
        return 'inShopDate <= :mandatory_date';
    }

    public function getParameters()
    {
        return [
            'mandatory_date'    => $this->mandatoryDate
        ];
    }
}
```

I looked where the problem could come from and I think it was due to [this commit](https://github.com/K-Phoen/rulerz/commit/71b21768d0e541607cfb3ba55ae25cc5bdfbcc46) because now the ObjectContext wrap the Datetime object.

So I created a fix for this : #88 

Be induglent, it's my first real PR and issue on github :).

**Comment by K-Phoen** [comment] 2017-09-18 11:49
As I explained in #88, I think that the problem isn't only linked to `DateTime` instances. It's linked to how rulerz handles arguments and operators.

**Comment by K-Phoen** [comment] 2017-09-20 07:33
Should be fixed in master :)

**Closed as completed** 2017-09-20 07:33 UTC
Labels: bug
