### ISSUE TITLE
Composite Type Error

### ISSUE THREAD

**Issue by bobdercole** [K-Phoen/rulerz#110] opened 2018-09-24 22:01 UTC
Hello,

A type error is thrown if Composite::getParameters() is called with zero parameters.

```
TypeError(code: 0): Return value of RulerZ\\Spec\\Composite::getParameters() must be of the type array, null returned at /application/vendor/kphoen/rulerz/src/Spec/Composite.php:76)
```

I think this has been returning null for awhile. It became apparent with the recent type hint additions.

**Comment by K-Phoen** [comment] 2018-09-25 14:54
Hello!

I tried to reproduce your issue in a test but I couldn't: 

https://github.com/K-Phoen/rulerz/blob/73abd298da7891b261f28d09b5370bfcd6cf0ab1/tests/spec/RulerZ/Spec/AndXSpec.php#L50-L58

Can you provide a minimal code sample that fails?

**Comment by bobdercole** [comment] 2018-09-25 16:29
Sorry, I should have specified that it fails with zero elements in the construct parameter.

https://github.com/bobdercole/rulerz/blob/6ab110654b5d28698386d9fdf93b0aa7f4ba6c59/tests/spec/RulerZ/Spec/AndXSpec.php#L50-L55

Here is the output:
```
Uncaught ArgumentCountError: array_merge() expects at least 1 parameter, 0 given in /mnt/c/Users/Bob/Code/rulerz/src/Spec/Composite.php:59
```

**Comment by K-Phoen** [comment] 2018-09-26 08:53
A composite specification with no components doesn't make much sense. I should have been more defensive when I wrote this class.

Anyway: a small fix landed on master. Can you review/test it?

https://github.com/K-Phoen/rulerz/blob/9f01bc7aade144a1ff82c20151019ff84f58d766/src/Spec/Composite.php#L59

**Comment by bobdercole** [comment] 2018-09-26 17:03
That works. Thank you!

I agree that this use case is a little strange. I am using RulerZ to dynamically build a specification based on the request. Sometimes the request does not add any specifications to the composite. Here is a simplified example:

```php
$specification = new \RulerZ\Spec\AndX();

if ($request->hasFilterOne())
{
	$specification->addSpecification(new FilterOneSpecification($request->getFilterOne()));
}

if ($request->hasFilterTwo())
{
	$specification->addSpecification(new FilterTwoSpecification($request->getFilterTwo()));
}

$repository->match($specification);
```

Thanks again.

**Comment by K-Phoen** [comment] 2018-09-28 21:22
Be careful: the `addSpecification()` will disappear in the 1.0.0 release (I just added a deprecation comment on this method).

I also encountered your use case and I built a list of specifications from the request, and if the list wasn't empty I used the `AndX`class to combine them. That will be the recommended way from now on :)

Btw, I close this issue since it's solved in master.

**Closed as completed by K-Phoen** 2018-09-28 21:22 UTC
